### PR TITLE
Retain original extension and add it to filename

### PR DESCRIPTION
**Pull request by oranges13**
This fixes the filename problem in #15

### CODE REVIEW

**Comment by jlegrone** [comment]
Oops, I didn't close #15 after the spec changed, this is no longer necessary. But thanks!

**Comment by jlegrone** [comment]
Wrong PR

**Comment by jlegrone** [comment]
Please merge from Bernie-2016/data-team-uploader :)

**Comment by oranges13** [comment]
This has been updated with the upstream changes! Ready to go!

**Comment by jlegrone** [comment]
Looks good, thanks!

**Pull request merged**
